# Generated by Django 3.2.5 on 2021-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_with_covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='symptoms.Symptoms'),
        ),
        migrations.AddField(
            model_name='user',
            name='travel_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
