# Generated by Django 3.2.5 on 2021-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210711_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_with_covid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
