# Generated by Django 3.2.5 on 2021-07-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_contact_with_covid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='travel_history',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
